name: carbon_emission_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.4.9
  freezed_annotation: ^3.0.0
  json_annotation: ^4.8.1
  retrofit: ^4.1.0
  riverpod_annotation: ^2.6.1
  percent_indicator: ^4.2.3
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  retrofit_generator: ^9.1.9
  build_runner: ^2.4.15
  riverpod_generator: ^2.6.5
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - .env

